@base=http://localhost:8080

### find pets by status
GET {{base}}/pet/findByStatus?status=available


### create pet
POST {{base}}/pet
Content-Type: application/json

{
  "name": "Bobi",
  "photoUrls": []
}



