name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:11
          apps: ""
      - run: |
          # check if there are any accidental diffs after regeneration, prevent overwrites
          ./scripts/check-accidental-overwrite.sh
          [ $? -eq 0 ]  || exit 1
          
          # check if there are any breaking changes
          ./scripts/openapi-diff.sh
          [ $? -eq 0 ]  || exit 1
