name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:11
          apps: []
      - run: |
          # check if there are any diffs after regeneration, prevent overwrites
          echo " " >> api/resources/openapi.yaml
          ./mill api.compile
          truncate -s -1 api/resources/openapi.yaml
          git diff --exit-code
          git_diff_status=$?
          exit $git_diff_status
          
          # check if there are any breaking changes
          ./scripts/check-breaking-changes.sh
